const PERSON_LIST_REQUEST_START ='PERSON_LIST_REQUEST_START';       
const PERSON_LIST_REQUEST_FAILED = 'PERSON_LIST_REQUEST_FAILED';       
const PERSON_LIST_REQUEST_SUCCESS = 'PERSON_LIST_REQUEST_SUCCESS';
            
const PERSON_CREATE_START = 'PERSON_CREATE_START';         
const PERSON_CREATE_FAILURE = 'PERSON_CREATE_FAILURE';         
const PERSON_CREATE_SUCCESS = 'PERSON_CREATE_SUCCESS';
            
const PERSON_EDIT_START = 'PERSON_EDIT_START';      
const PERSON_EDIT_FAILURE = 'PERSON_EDIT_FAILURE';       
const PERSON_EDIT_SUCCESS = 'PERSON_EDIT_SUCCESS';
            
const PERSON_DELETE_START = 'PERSON_DELETE_START';       
const PERSON_DELETE_FAILURE = 'PERSON_DELETE_FAILURE';     
const PERSON_DELETE_SUCCESS = 'PERSON_DELETE_SUCCESS';
            
const types = {
    PERSON_LIST_REQUEST_START,
    PERSON_LIST_REQUEST_FAILED,
    PERSON_LIST_REQUEST_SUCCESS,
    
    PERSON_CREATE_START,
    PERSON_CREATE_FAILURE,
    PERSON_CREATE_SUCCESS,
    
    PERSON_EDIT_START,
    PERSON_EDIT_FAILURE,
    PERSON_EDIT_SUCCESS,
    
    PERSON_DELETE_START,
    PERSON_DELETE_FAILURE,
    PERSON_DELETE_SUCCESS,
}

export default types;