const MOVIE_LIST_REQUEST_START = 'MOVIE_LIST_REQUEST_START';
const MOVIE_LIST_REQUEST_FAILED = 'MOVIE_LIST_REQUEST_FAILED';
const MOVIE_LIST_REQUEST_SUCCESS = 'MOVIE_LIST_REQUEST_SUCCESS';

const MOVIE_CREATE_START = 'MOVIE_CREATE_START';
const MOVIE_CREATE_FAILURE = 'MOVIE_CREATE_FAILURE';
const MOVIE_CREATE_SUCCESS = 'MOVIE_CREATE_SUCCESS';

const MOVIE_EDIT_START = 'MOVIE_EDIT_START';
const MOVIE_EDIT_FAILURE = 'MOVIE_EDIT_FAILURE';
const MOVIE_EDIT_SUCCESS = 'MOVIE_EDIT_SUCCESS';
        
const MOVIE_DELETE_START = 'MOVIE_DELETE_START';
const MOVIE_DELETE_FAILURE = 'MOVIE_DELETE_FAILURE';
const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS';
        
const MOVIE_DIRECTOR_SET_START = 'MOVIE_DIRECTOR_SET_START';
const MOVIE_DIRECTOR_SET_FAILURE = 'MOVIE_DIRECTOR_SET_FAILURE';
const MOVIE_DIRECTOR_SET_SUCCESS = 'MOVIE_DIRECTOR_SET_SUCCESS';
            
const MOVIE_REQUEST_START = 'MOVIE_REQUEST_START';    
const MOVIE_REQUEST_FAILED = 'MOVIE_REQUEST_FAILED';     
const MOVIE_REQUEST_SUCCESS = 'MOVIE_REQUEST_SUCCESS';


const types = {
    MOVIE_LIST_REQUEST_START, 
    MOVIE_LIST_REQUEST_FAILED,
    MOVIE_LIST_REQUEST_SUCCESS,
    
    MOVIE_CREATE_START,
    MOVIE_CREATE_FAILURE,
    MOVIE_CREATE_SUCCESS,

    MOVIE_EDIT_START,
    MOVIE_EDIT_FAILURE,
    MOVIE_EDIT_SUCCESS,      
        
    MOVIE_DELETE_START,    
    MOVIE_DELETE_FAILURE,  
    MOVIE_DELETE_SUCCESS,
            
    MOVIE_DIRECTOR_SET_START,
    MOVIE_DIRECTOR_SET_FAILURE,
    MOVIE_DIRECTOR_SET_SUCCESS,
            
    MOVIE_REQUEST_START,
    MOVIE_REQUEST_FAILED,
    MOVIE_REQUEST_SUCCESS,       
}

export default types;